rmmod i82540EM.ko
python3 main.py
python3 main.py
python3 main.py
python3 main.py
python3 main.py
python3 main.py
python3 main.py
insmod i82540EM.ko
python3 main.py
python3 main.py
python3 main.py
python3 main.py
python3 main.py
python3 main.py
python3 main.py
python3 main.py
rmmod i82540EM.ko
insmod i82540EM.ko
python3 main.py
python3 main.py
python3 main.py
python3 main.py
python3 main.py
python3 main.py
python3 main.py
python3 main.py

